[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"
gas_reports = ["Router","LibBytes","LibSafeTransfer"]
fs_permissions = []

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

[profile.ci]
verbosity = 4
