name: ci
on:
  push:
  pull_request:
jobs:
  solidity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install deps
        run: forge install foundry-rs/forge-std@v1.9.5 --no-commit
      - name: Build
        run: forge build
      - name: Test
        run: forge test -vv
  bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src-bot
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci || npm i
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint || true
