name: ci
on:
  push:
  pull_request:
jobs:
  solidity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Fetch forge-std (no forge install)
        run: |
          mkdir -p lib
          git clone --depth 1 https://github.com/foundry-rs/forge-std lib/forge-std
          ls -la lib
      - name: Build (contracts + scripts)
        run: forge build
  bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src-bot
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci || npm i
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint || true
